name: card_nudge
description: A Flutter app for managing credit card dues.
publish_to: 'none'
version: 0.5.4+44
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown_plus: ^1.0.3
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_test:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  uuid: ^4.0.0
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.4.0
  flutter_svg: ^2.1.0
  go_router: ^15.1.2
  fl_chart: ^1.0.0
  flutter_colorpicker: ^1.1.0
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.2.1
  google_sign_in: ^6.3.0
  connectivity_plus: ^6.1.4
  package_info_plus: ^8.3.0
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  firebase_messaging: ^15.2.7
  firebase_core: ^3.14.0
  device_info_plus: ^11.5.0
  firebase_performance: ^0.10.1+8

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/bank_icons/
    - assets/card_networks_icons/
