// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVzPbJVSV1jj4W7a1PAuCHWnn39Htoh8I',
    appId: '1:896348195696:web:ea8f12decb18612dc69db5',
    messagingSenderId: '896348195696',
    projectId: 'in-fnlsg-card',
    authDomain: 'in-fnlsg-card.firebaseapp.com',
    storageBucket: 'in-fnlsg-card.firebasestorage.app',
    measurementId: 'G-WRM8FTR8RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS4mY4TVCh3-QFLvdJ6WBmUQT-vMgGLaA',
    appId: '1:896348195696:android:116c4a9f8975ef07c69db5',
    messagingSenderId: '896348195696',
    projectId: 'in-fnlsg-card',
    storageBucket: 'in-fnlsg-card.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Cs4_V9RIn61208rNQzouKJwXNCZjFMU',
    appId: '1:896348195696:ios:21ebf4cc405f21d1c69db5',
    messagingSenderId: '896348195696',
    projectId: 'in-fnlsg-card',
    storageBucket: 'in-fnlsg-card.firebasestorage.app',
    iosBundleId: 'in.fnlsg.card',
  );

}